services:

  emqx: 
    image: emqx:latest
    container_name: emqx
    ports:
      - 1883:1883
      - 18083:18083
    networks:
      - rede

    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rede
    depends_on:
      - emqx
  
  mongodb:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    networks:
      - rede
    depends_on:
      - rabbitmq
  
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8075:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=1234
    networks:
      - rede
    depends_on:
      - mongodb

volumes:
  mongodb_data:

networks:
  rede:
